# -*- coding: utf-8 -*-
"""BASIC PROBABILITY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11z6P5brtfgGaiALXNBNktiSTm8NskVhY
"""

from fractions import Fraction

white_P = Fraction(5, 9)
black_P = Fraction(4, 9)

black_Pw = Fraction(6, 14)
black_Pb = Fraction(7, 14)

Pb = white_P * black_Pw + black_P * black_Pb
print(Pb)

